---
title: 'Case study'
author: 'Jefferson Ong'
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document:
    theme: united
    highlight: tango
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
---

```{r, echo = FALSE}
library(tidyverse)
library(purrr)
library(Lahman)
library(resampledata)
```



```{r}
# # Examine lahmanNames
# lahmanNames
# 
# # Find variables in common
# reduce(lahmanNames, intersect)
```

```{r}
# lahmanNames %>%  
#   # Bind the data frames in lahmanNames
#   bind_rows(.id = "dataframe") %>%
#   # Group the result by var
#   group_by(var) %>%
#   # Tally the number of appearances
#   tally() %>%
#   # Filter the data
#   filter(n > 1) %>% 
#   # Arrange the results
#   arrange(desc(n))
```

```{r}
# lahmanNames %>% 
#   # Bind the data frames
#   bind_rows(.id = "dataframe") %>%
#   # Filter the results
#   filter(var == "playerID") %>%
#   # Extract the dataframe variable
#   `$`("dataframe")
```


```{r}
# players <- Master %>% 
#   # Return one row for each distinct player
#   distinct(playerID, nameFirst, nameLast)
# 
# 
# players %>% 
#   # Find all players who do not appear in Salaries
#   anti_join(Salaries, by = "playerID") %>%
#   # Count them
#   count()
```



```{r}
# players %>% 
#   # Find all players who do not appear in Salaries
#   anti_join(Salaries, by = "playerID") %>% 
#   # Join them to Appearances
#   left_join(Appearances, by = "playerID") %>%
#   # Calculate total_games for each player
#   group_by(playerID) %>% 
#   summarize(total_games = sum(G_all, na.rm = TRUE)) %>%
#   # Arrange in descending order by total_games
#   arrange(desc(total_games))
```


```{r}
# players %>%
#   # Find unsalaried players
#   anti_join(Salaries, by = "playerID") %>% 
#   # Join Batting to the unsalaried players
#   left_join(Batting, by = "playerID") %>% 
#   # Group by player
#   group_by(playerID) %>% 
#   # Sum at-bats for each player
#   summarize(total_at_bat = sum(AB, na.rm = TRUE)) %>% 
#   # Arrange in descending order
#  arrange(desc(total_at_bat))
```







```{r}
# Find the distinct players that appear in HallOfFame
# nominated <- HallOfFame %>% 
#   distinct(playerID)
# 
# nominated %>% 
#   # Count the number of players in nominated
#   count()
# 
# nominated_full <- nominated %>% 
#   # Join to Master
#   left_join(Master, by = "playerID") %>% 
#   # Return playerID, nameFirst, nameLast
#  select(playerID, nameFirst, nameLast)
```



```{r}
# Find distinct players in HallOfFame with inducted == "Y"
# inducted <- HallOfFame %>% 
#   filter(inducted == "Y") %>% 
#   distinct(playerID)
# 
# inducted %>% 
#   # Count the number of players in inducted
#   count()
# 
# inducted_full <- inducted %>% 
#   # Join to Master
#   left_join(Master, by = "playerID") %>% 
#   # Return playerID, nameFirst, nameLast
#   select(playerID, nameFirst, nameLast)
```

```{r}
# Tally the number of awards in AwardsPlayers by playerID
# nAwards <- AwardsPlayers %>% 
#   group_by(playerID) %>% 
#   tally()
# 
# nAwards %>% 
#   # Filter to just the players in inducted 
#   semi_join(inducted, by = "playerID") %>% 
#   # Calculate the mean number of awards per player
#   summarize(avg_n = mean(n, na.rm = TRUE))
# 
# nAwards %>% 
#   # Filter to just the players in nominated 
#   semi_join(nominated, by = "playerID") %>%
#   # Filter to players NOT in inducted 
#   anti_join(inducted, by = "playerID") %>%
#   # Calculate the mean number of awards per player
#  summarize(avg_n = mean(n, na.rm = TRUE))
```


```{r}
# Find the players who are in nominated, but not inducted
# notInducted <- nominated %>% 
#   setdiff(inducted)
# 
# Salaries %>% 
#   # Find the players who are in notInducted
#   semi_join(notInducted, by = "playerID") %>%
#   # Calculate the max salary by player
#   group_by(playerID) %>% 
#   summarize(max_salary = max(salary, na.rm = TRUE)) %>% 
#   # Calculate the average of the max salaries
#   summarize(avg_salary = mean(max_salary, na.rm = TRUE))
# 
# # Repeat for players who were inducted
# Salaries %>% 
#   semi_join(inducted, by = "playerID") %>% 
#   group_by(playerID) %>% 
#   summarize(max_salary = max(salary, na.rm = TRUE)) %>% 
#  summarize(avg_salary = mean(max_salary, na.rm = TRUE))
```



```{r}
# Appearances %>% 
#   # Filter Appearances against nominated
#   semi_join(nominated, by = "playerID") %>% 
#   # Find last year played by player
#   group_by(playerID) %>% 
#   summarize(last_year = max(yearID)) %>% 
#   # Join to full HallOfFame
#   left_join(HallOfFame, by = "playerID") %>% 
#   # Filter for unusual observations
#   filter(last_year >= yearID)
```







































